# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Parse开源文档
title: Parse中文文档
email: community@parse.com
description: Parse平台的开源GitHub页面。
baseurl: /parse-doc-zh # the subpath of your site, e.g. /blog
url: "https://myark.github.io/parse-doc-zh" # the base hostname & protocol for your site
repository: myark/parse-doc-zh
facebook_username: parseit
twitter_username:  parseit
github_username:   parseplatform
stackoverflow_tag: parse.com
serverfault_tag:   parse
support_url: https://www.parse.com/help

# Build settings
markdown: kramdown
exclude: [ Gemfile, Gemfile.lock, README.md, config.codekit, webpack.config.js, node_modules, npm-debug.log, package.json ]
sass:
    sass_dir: css

# Gems
gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
